site_name: momapy_kb
site_url: https://adrienrougny.github.io/momapy_kb/
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Demo: neo4j/main.ipynb
  - API reference:
    - Core: api_reference/core.md
    - Utils: api_reference/utils.md
    - LPG:
      - Session: api_reference/lpg/session.md
      - Types: api_reference/lpg/types.md
      - Utils: api_reference/lpg/utils.md
      - Backends:
        - Neo4j: api_reference/lpg/backends/neo4j.md
        - FalkorDB: api_reference/lpg/backends/falkordb.md
        - FalkorDBLite: api_reference/lpg/backends/falkordblite.md
    - Clingo:
      - Session: api_reference/clingo/session.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            inherited_members: true
            group_by_category: false
            show_category_heading: false
            show_root_heading: true
            parameter_headings: false
            show_signature_annotations: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            signature_crossrefs: true
            merge_init_into_class: true
            summary: true
            extensions:
              - griffe_fieldz: {include_inherited: true}
              - griffe_inherited_docstrings
markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
