[project]
name = "momapy_kb"
version = "0.1.0"
description = "Momapy maps to KB"
authors = [{ name = "Adrien Rougny", email = "adrienrougny@gmail.com" }]
dependencies = [
  "colorama>=0.4.6",
  "jinja2>=3.1.3",
  "frozendict>=2.4.6",
  "momapy",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
clingo = ["fieldz-kb[clingo]"]
neo4j = ["fieldz-kb[neo4j]"]
falkordb = ["fieldz-kb[falkordb]"]
falkordblite = ["fieldz-kb[falkordblite]"]
all = ["momapy_kb[clingo,neo4j,falkordb,falkordblite]"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["notebook>=7.4.7"]

[tool.uv.sources]
momapy = { path = "../momapy", editable = true }
fieldz-kb = { workspace = true, editable = true }

[tool.uv.workspace]
members = ["fieldz_kb"]
