[tox]
envlist = py{310,311,312,313,314}
skip_missing_interpreters = false

[testenv]
description = Run tests with pytest
dependency_groups = test
extras = all
commands =
    pytest {posargs:tests/}

[testenv:coverage]
description = Run tests with coverage report
dependency_groups = test
extras = all
commands =
    pytest --cov=momapy_kb --cov-report=term --cov-report=html {posargs:tests/}
